language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nikola/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nikola/react-test npm test

after_success:
  - docker build -t nikola/multi-client ./client
  - docker build -t nikola/multi-nginx ./nginx
  - docker build -t nikola/multi-server ./server
  - docker build -t nikola/multi-worker ./worker
